In [3]:
!pip install pandas
import pandas as pd

Collecting pandas
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.22.4 (from pandas)
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\rdp_automation\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\rdp_automation\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]

In [33]:
df = pd.read_csv(r'C:\customer_support_system\Customer_support_system\data\flipkart_product_review.csv')

In [34]:
df.head()

,product_id,product_title,rating,summary,review
0,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,1-more flexible2-bass is very high3-sound clar...
1,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Super sound and good looking I like that prize
2,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,Very much satisfied with the device at this pr...
3,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,"Nice headphone, bass was very good and sound i..."
4,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Sound quality super battery backup super quali...

In [35]:
df.columns

Index(['product_id', 'product_title', 'rating', 'summary', 'review'], dtype='object')

In [36]:
for index, row in df.iterrows():
    print(row['product_title'])
    #print(index)

BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
realme Buds Wireless Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
OnePlus Bullets Wireless Z Bluetooth Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
realme Buds 2 Wired Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
realme Buds Q Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
U&I Titanic Series - Low Price Bluetooth Neckband Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt Airdopes 131 Bluetooth Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset
BoAt BassHeads 100 Wired Headset

In [42]:
df = df.reset_index(drop=True)

In [43]:
df

,product_id,product_title,rating,summary,review
0,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,1-more flexible2-bass is very high3-sound clar...
1,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Super sound and good looking I like that prize
2,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,Very much satisfied with the device at this pr...
3,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,"Nice headphone, bass was very good and sound i..."
4,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Sound quality super battery backup super quali...
...,...,...,...,...,...
445,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,5,Wonderful,nice product.. color is exactly shown in the ...
446,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,5,Brilliant,Awesome Headset . I was searching for the same...
447,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,3,Fair,It's a really perfect earphone. I love it . So...
448,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,4,Value-for-money,Good earbuds at this price Range and Boat prov...
449,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,4,Wonderful,a very good earphone in budget sound is awesom...